server:
  port: 8081 # El puerto de este microservicio

spring:
  application:
    name: catalogue
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/books_catalogue?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate # Esquema definido en books_catalogue.sql (IDs INT)
    show-sql: true # Para ver las consultas en consola

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    # Forzamos que el ID de registro en Eureka sea con la IP y el puerto
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}